DROP TABLE IF EXISTS dechets;
CREATE TABLE dechets (id_dechet INTEGER primary key,nomFR TEXT,nomEN TEXT,nomImage TEXT,type TEXT);
INSERT INTO dechets VALUES(0,"Barquette confiture","Jam tray","menager_barquette_plastique_confiture","menager");
INSERT INTO dechets VALUES(1,"Sac plastique","Bag","menager_sacplastique","menager");
INSERT INTO dechets VALUES(2,"Journaux","News papers","recyclable_journaux","recyclable");
INSERT INTO dechets VALUES(3,"Gourde compote","stewed gourd","menager_compote","menager");
INSERT INTO dechets VALUES(4,"Couche bébé","baby diaper","menager_couche","menager");
INSERT INTO dechets VALUES(5,"Sachet de chips","bag of chips","menager_sachetchips","menager");
INSERT INTO dechets VALUES(6,"Boite de céréales","Cereal box","recyclable_boitecereale","recyclable");
INSERT INTO dechets VALUES(7,"Bouteille d'eau","bottle of water","recyclable_bouteilleeau","recyclable");
INSERT INTO dechets VALUES(8,"Canette de Soda","can of soda","recyclable_canettesoda","recyclable");
INSERT INTO dechets VALUES(9,"Conserve","canned food","recyclable_conserve","recyclable");
INSERT INTO dechets VALUES(10,"Sirop","syrup","recyclable_sirop","recyclable");
INSERT INTO dechets VALUES(11,"Cahier","notebook","recyclable_cahier","recyclable");
INSERT INTO dechets VALUES(12,"Shampoing","shampoo","recyclable_shampoing","recyclable");
INSERT INTO dechets VALUES(13,"Pochette Cadeau","gift bag","recyclable_pochettecadeau","recyclable");
INSERT INTO dechets VALUES(14,"Ketchup","Ketchup","recyclable_ketchup","recyclable");
INSERT INTO dechets VALUES(15,"Briquette de Jus d'orange","briquette of orange juice","recyclable_briquettejusorange","recyclable");
INSERT INTO dechets VALUES(16,"Tube de dentifrice","tube of toothpaste","menager_dentifrice","menager");
INSERT INTO dechets VALUES(17,"Assiette cassée","Brocken plate","menager_assiettecassee","menager");
INSERT INTO dechets VALUES(18,"Gobelet plastique","plastic cup","menager_gobeletplastique","menager");
INSERT INTO dechets VALUES(19,"boite à chaussure","shoebox","recyclable_boitechaussure","recyclable");
INSERT INTO dechets VALUES(20,"brick de lait","milk brig","recyclable_bricklait","recyclable");
INSERT INTO dechets VALUES(21,"Emballage de Lessive vide","Empty laundry package","recyclable_lessive","recyclable");
INSERT INTO dechets VALUES(22,"Pot de Crème Fraiche","jar of fresh cream","menager_cremefraiche","menager");
INSERT INTO dechets VALUES(23,"Restes de Repas","leftovers","menager_restederepas","menager");
INSERT INTO dechets VALUES(24,"Pub","advert","recyclable_pub","recyclable");